New code
AndreiBakhtinov/190923 pull request #38
Opened 2024-02-14 11:40 UTC by sulida

2024-02-14 11:40 UTC, AndreiBakhtinov requested changes
не соответствует задачи

2024-02-14 11:41 UTC, Lightoton requested changes
не тот запрос

2024-02-14 11:50 UTC, natol2023 approved these changes

2024-02-14 11:50 UTC, a-harbuz approved these changes
Good!

2024-02-14 23:19 UTC, Pashora approved these changes
Good job!

2024-02-14 23:24 UTC, Lightoton approved these changes

2024-02-19 12:29 UTC, AndreiBakhtinov approved these changes

2024-02-19 12:57 UTC, merged